version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      #- rabbit
    environment:
      SPRING_PROFILES_ACTIVE: docker

      # ===== DATASOURCE =====
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345

      # ===== RABBITMQ =====
      #SPRING_RABBITMQ_HOST: rabbit
      #SPRING_RABBITMQ_PORT: 5672
      #SPRING_RABBITMQ_USERNAME: guest
      #SPRING_RABBITMQ_PASSWORD: guest

  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    ports:
      - "5050:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  #rabbit:
    #image: rabbitmq:3-management
    #container_name: rabbitmq
    #restart: always
    #ports:
     # - "5672:5672"
     # - "15672:15672"

volumes:
  postgres_data:
